Repository dku25-capstone/chatGraph-BE, pull requests merged in 2025-07, with the labels that each got.

#17 fix(security): HTTP 인가 임시 모두 허용
  src/main/java/dku25/chatGraph/api/config/SecurityConfig.java
Labels: feat

#28 Fix/yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#39 Feat/corsconfig, CORS 관련 수정
  nginx/nginx.conf
  src/main/java/dku25/chatGraph/api/config/SecurityConfig.java
  src/main/java/dku25/chatGraph/api/util/JwtAuthenticationFilter.java
Labels: infra

#49 fix: ServiceRefactoring
  src/main/java/dku25/chatGraph/api/controller/QuestionController.java
  src/main/java/dku25/chatGraph/api/controller/TopicController.java
  src/main/java/dku25/chatGraph/api/controller/UserController.java
  src/main/java/dku25/chatGraph/api/graph/node/TopicNode.java
  src/main/java/dku25/chatGraph/api/graph/repository/UserNodeRepository.java
  src/main/java/dku25/chatGraph/api/graph/service/AnswerService.java
  src/main/java/dku25/chatGraph/api/graph/service/GraphService.java
  src/main/java/dku25/chatGraph/api/graph/service/QuestionService.java
  src/main/java/dku25/chatGraph/api/graph/service/TopicService.java
  src/main/java/dku25/chatGraph/api/graph/service/UserNodeService.java
  src/main/java/dku25/chatGraph/api/openai/service/OpenaiService.java
Labels: refactor

#58 mod:refactoring
  src/main/java/dku25/chatGraph/api/graph/dto/QuestionAnswerDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/QuestionNodeMapDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/TopicTreeMapResponseDTO.java
  src/main/java/dku25/chatGraph/api/graph/service/NodeUtilService.java
  src/main/java/dku25/chatGraph/api/openai/dto/AskResponse.java
  src/main/java/dku25/chatGraph/api/openai/service/OpenaiService.java
Labels: refactor

#59 mod: refactoring
  src/main/java/dku25/chatGraph/api/controller/QuestionController.java
  src/main/java/dku25/chatGraph/api/controller/TopicController.java
  src/main/java/dku25/chatGraph/api/graph/dto/NodeRenameRequestDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/NodeRenameResponseDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/RenameQuestionRequestDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/RenameQuestionResponseDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/RenameTopicResponseDTO.java
  src/main/java/dku25/chatGraph/api/graph/repository/QuestionRepository.java
  src/main/java/dku25/chatGraph/api/graph/repository/TopicRepository.java
  src/main/java/dku25/chatGraph/api/graph/service/GraphService.java
  src/main/java/dku25/chatGraph/api/graph/service/NodeUtilService.java
  src/main/java/dku25/chatGraph/api/graph/service/QuestionService.java
  src/main/java/dku25/chatGraph/api/graph/service/TopicService.java
  src/main/java/dku25/chatGraph/api/openai/service/OpenaiService.java
Labels: refactor

#62 Mod/column
  src/main/java/dku25/chatGraph/api/controller/OpenaiController.java
  src/main/java/dku25/chatGraph/api/graph/dto/QuestionAnswerDTO.java
  src/main/java/dku25/chatGraph/api/graph/dto/RenameQuestionResponseDTO.java
  src/main/java/dku25/chatGraph/api/graph/repository/QuestionRepository.java
  src/main/java/dku25/chatGraph/api/graph/repository/TopicRepository.java
  src/main/java/dku25/chatGraph/api/graph/service/NodeUtilService.java
  src/main/java/dku25/chatGraph/api/openai/dto/AskRequest.java
Labels: refactor
